#ifndef TRIPLUGININTERFACE_GLOBAL_H
#define TRIPLUGININTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRIPLUGININTERFACE_LIBRARY)
#  define TRIPLUGININTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define TRIPLUGININTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TRIPLUGININTERFACE_GLOBAL_H
